name: Project Card動かされたら実行

on:
  project_card:
    types: [moved]

jobs:
#  check-card:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: chekcout
#        uses: actions/checkout@v2
#
#      - name: 動かされたカード情報
#        run: echo "カードid ${{ github.event.project_card.id }} が移動されました"
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "カードid ${{ github.event.project_card.id }} が移動されました"
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}