name: テスト実行

on: push

jobs:
  test:

    # 最初からPHPとComposerが入ってるみたい
    runs-on: ubuntu-latest

    steps:
      - name: 1.PHPのバージョン確認
        run: php -v

      - name: 2.Compoerのバージョン確認
        run: composer -V

      - name: 3.chekcout
        uses: actions/checkout@v2

      - name: 4.composerでインストールしたものをキャッシュする
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: 5.composer install
        run: composer install

      - name: 6.ユニットテストの実行
        run: ./vendor/bin/phpunit ./tests
