name: テスト実行

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: PHPのバージョン確認
        run: php -v
      - name: Compoerのバージョン確認
        run: composer -V

#      - uses: actions/checkout@v2

#      - name: Validate composer.json and composer.lock
#        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: ./vendor/bin/phpunit .
